spring:
  application:
    name: sb1-hrbank-team03
  datasource:
    url: jdbc:postgresql://localhost:5432/hrbank
    username: public_user
    password: 1234
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

hrbank:
  storage:
    type: local
    local:
      root-path: .hrbank/data

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE

backup:
  scheduler:
    enabled: true
  interval:
    milliseconds: 3600000