spring:
  application:
    name: sb1-hrbank-team03
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

hrbank:
  storage:
    type: local
    local:
      root-path: ${HRBANK_STORAGE_ROOT_PATH}

backup:
  scheduler:
    enabled: ${BACKUP_SCHEDULER_ENABLED}
  interval:
    milliseconds: ${BACKUP_INTERVAL_MS}

server:
  forward-headers-strategy: native

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE